### PR TITLE
Full code review and add gradle plugins 

### PR DESCRIPTION
**Pull request by bschlosser**
Gradle plugins: checkstyle, spotbugs, jacoco(test coverage), and dependency vulnerability scan

### CODE REVIEW

**Comment by joewarner** [comment]
The description of the build variable `REST_WORKER_ID` is incomplete in the README. I'm not sure what this was now - was it meant to be the 'topic' that the worker would listen on?

**Comment by bschlosser** [comment]
> The description of the build variable `REST_WORKER_ID` is incomplete in the README. I'm not sure what this was now - was it meant to be the 'topic' that the worker would listen on?

@shardingbp3 can you help us understand the intent of that variable?

**Comment by jphillips-bp3** [comment]
> > The description of the build variable `REST_WORKER_ID` is incomplete in the README. I'm not sure what this was now - was it meant to be the 'topic' that the worker would listen on?
> 
> @shardingbp3 can you help us understand the intent of that variable?

Yes, and is referenced in the `application.properties` file as follows:

```
# Identifies the worker towards the Engine
camunda.bpm.client.worker-id=${REST_WORKER_ID:bp3-http-json}
```

But the code itself then hardcodes the subscription Id anyway so whatever you set it to it would be ingored:
```
@ExternalTaskSubscription("bp3-http-json")
```

**Comment by shardingbp3** [comment]
Justin is absolutely right... the environment variable is not used.  I have removed it.

**Comment by shardingbp3** [comment]
When building I am getting an error:
Could not get unknown property 'nistNvdApiKey' for object of type org.owasp.dependencycheck.gradle.extension.NvdExtension.

**Comment by joewarner** [comment]
I think the pipeline only runs when there is a release. But I think we should probably be doing a build/unit-test on each commit as well. Not exactly sure of the best way to do that - does it want a separate YAML file that just runs build/unit-test for every commit that isn't a release? Maybe this is one for @jphillips-bp3?

**Comment by jphillips-bp3** [comment]
What is happening with this PR? Is the code / release process broken or can it be merged?

**Comment by bschlosser** [comment]
@jphillips-bp3 CamundaCon happened and I was short on time. I'm happy with this now and ready to merge if you are. @shardingbp3 I've addressed the build problem you reported.

**Pull request merged**
